name: april_flutter_screen_adapter
description: A Flutter version of the screen adaptation package.
version: 1.4.0
homepage: 'https://github.com/AAAAAApril/april_flutter_screen_adapter'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

# 发布插件命令
# flutter packages pub publish --server=https://pub.dartlang.org
